version: '3.7'
services:
  mongo:
    image: mongo:4.0
    volumes:
      - ./docker/mongodb-data:/data/db
    ports:
      - '27017:27017'

  zookeeper:
    image: zookeeper:3.4
    labels:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:30992
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://localhost:30992
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_BROKER_ID=1

      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS=nevents_in:1:1,connections:1:1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_DELETE_TOPIC_ENABLE=true

      - KAFKA_LOG_RETENTION_BYTES=200000000
      - KAFKA_LOG_SEGMENT_BYTES=20000000
    expose:
      - 9092
      - 30992
    ports:
      - '30992:30992'

